version: '{build}'
skip_tags: true
clone_depth: 10
environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
install:
  # Prepend Maven and Java entries, remove Ruby entry (C:\Ruby193\bin;) from PATH
  - cmd: choco upgrade maven
  - cmd: SET PATH=JAVA_HOME%\bin;%PATH:C:\Ruby193\bin;=%;
  - cmd: SET MAVEN_OPTS=-XX:MaxPermSize=1g -Xmx2g
  - cmd: SET JAVA_OPTS=-XX:MaxPermSize=1g -Xmx2g
  - cmd: C:\ProgramData\chocolatey\bin\mvn.exe --version
  - cmd: java -version
build_script:
  - C:\ProgramData\chocolatey\bin\mvn.exe clean install
cache:
  - C:\maven\ -> appveyor.yml
  - C:\Users\appveyor\.m2\ -> pom.xml
